#!/bin/sh

SESSION_NAME="";

function usage()
{
echo "usage: $0 [-s session-name]"
}
# Parse arguments
while getopts hs: PARAM; do
    case "$PARAM" in
        h)
            usage
            exit
            ;;
        s)
            SESSION_NAME="$OPTARG"
            ;;
        *)
            echo "$0: unknown option \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

$SESSION_NAME=`echo $SESSION_NAME | awk -F. '{print $1}'`;
echo "Session name is $SESSION_NAME"
# # Create Tmux session
# if ! tmux has-session -t $SESSION_NAME; then
# echo "creating new session $SESSION_NAME"
# tmux new -s $SESSION_NAME -d
#     # Prepeare for attach
#     tmux new-window -t $SESSION_NAME:2
#     tmux split-window -t $SESSION_NAME:2 -v
#     tmux send-keys -t $SESSION_NAME:1 vim Enter
# fi
# tmux attach -t $SESSION_NAME

# # Start recording timew
# echo "recording session start time";
# timew start $SESSION_NAME;
